// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi A clickhouse-swagger application
Shows how swagger and Clickhouse works together


    Schemes:
      http
    Host: localhost
    BasePath: /v1.0
    Version: 1.0.0

    Consumes:
    - application/io.goswagger.metrics-app.v1+json

    Produces:
    - application/io.goswagger.metrics-app.v1+json

swagger:meta
*/
package restapi
