// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/io.goswagger.metrics-app.v1+json"
  ],
  "produces": [
    "application/io.goswagger.metrics-app.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Shows how swagger and Clickhouse works together",
    "title": "A clickhouse-swagger application",
    "version": "1.0.0"
  },
  "basePath": "/v1.0",
  "paths": {
    "/metrics": {
      "get": {
        "description": "Get metrics for the time range",
        "tags": [
          "metrics"
        ],
        "summary": "Get metrics for the time range",
        "operationId": "findMetrics",
        "parameters": [
          {
            "type": "string",
            "format": "date-time",
            "description": "Start of time range",
            "name": "from",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "End of time range",
            "name": "to",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "object",
                "properties": {
                  "datapoints": {
                    "type": "integer"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid tag value"
          }
        }
      }
    },
    "/metrics/{metricName}": {
      "post": {
        "description": "Save datapoint",
        "tags": [
          "metrics"
        ],
        "summary": "Save datapoint",
        "operationId": "postDatapoint",
        "parameters": [
          {
            "minLength": 1,
            "type": "string",
            "name": "metricName",
            "in": "path",
            "required": true
          },
          {
            "description": "Dattime range",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Datapoint"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Datapoint": {
      "type": "object",
      "required": [
        "timestamp_utc",
        "value"
      ],
      "properties": {
        "timestamp_utc": {
          "type": "integer",
          "format": "int64"
        },
        "value": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Metric": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "datapoints": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Datapoint"
          }
        },
        "name": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your Metrics",
      "name": "metrics",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/io.goswagger.metrics-app.v1+json"
  ],
  "produces": [
    "application/io.goswagger.metrics-app.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Shows how swagger and Clickhouse works together",
    "title": "A clickhouse-swagger application",
    "version": "1.0.0"
  },
  "basePath": "/v1.0",
  "paths": {
    "/metrics": {
      "get": {
        "description": "Get metrics for the time range",
        "tags": [
          "metrics"
        ],
        "summary": "Get metrics for the time range",
        "operationId": "findMetrics",
        "parameters": [
          {
            "type": "string",
            "format": "date-time",
            "description": "Start of time range",
            "name": "from",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "End of time range",
            "name": "to",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "object",
                "properties": {
                  "datapoints": {
                    "type": "integer"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid tag value"
          }
        }
      }
    },
    "/metrics/{metricName}": {
      "post": {
        "description": "Save datapoint",
        "tags": [
          "metrics"
        ],
        "summary": "Save datapoint",
        "operationId": "postDatapoint",
        "parameters": [
          {
            "minLength": 1,
            "type": "string",
            "name": "metricName",
            "in": "path",
            "required": true
          },
          {
            "description": "Dattime range",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Datapoint"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Datapoint": {
      "type": "object",
      "required": [
        "timestamp_utc",
        "value"
      ],
      "properties": {
        "timestamp_utc": {
          "type": "integer",
          "format": "int64"
        },
        "value": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Metric": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "datapoints": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Datapoint"
          }
        },
        "name": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your Metrics",
      "name": "metrics",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    }
  ]
}`))
}
