// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// FindMetricsOKCode is the HTTP code returned for type FindMetricsOK
const FindMetricsOKCode int = 200

/*FindMetricsOK successful operation

swagger:response findMetricsOK
*/
type FindMetricsOK struct {

	/*
	  In: Body
	*/
	Payload map[string]FindMetricsOKBodyAnon `json:"body,omitempty"`
}

// NewFindMetricsOK creates FindMetricsOK with default headers values
func NewFindMetricsOK() *FindMetricsOK {

	return &FindMetricsOK{}
}

// WithPayload adds the payload to the find metrics o k response
func (o *FindMetricsOK) WithPayload(payload map[string]FindMetricsOKBodyAnon) *FindMetricsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find metrics o k response
func (o *FindMetricsOK) SetPayload(payload map[string]FindMetricsOKBodyAnon) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindMetricsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]FindMetricsOKBodyAnon, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// FindMetricsBadRequestCode is the HTTP code returned for type FindMetricsBadRequest
const FindMetricsBadRequestCode int = 400

/*FindMetricsBadRequest Invalid tag value

swagger:response findMetricsBadRequest
*/
type FindMetricsBadRequest struct {
}

// NewFindMetricsBadRequest creates FindMetricsBadRequest with default headers values
func NewFindMetricsBadRequest() *FindMetricsBadRequest {

	return &FindMetricsBadRequest{}
}

// WriteResponse to the client
func (o *FindMetricsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
