// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostDatapointCreatedCode is the HTTP code returned for type PostDatapointCreated
const PostDatapointCreatedCode int = 201

/*PostDatapointCreated Created

swagger:response postDatapointCreated
*/
type PostDatapointCreated struct {
}

// NewPostDatapointCreated creates PostDatapointCreated with default headers values
func NewPostDatapointCreated() *PostDatapointCreated {

	return &PostDatapointCreated{}
}

// WriteResponse to the client
func (o *PostDatapointCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostDatapointInternalServerErrorCode is the HTTP code returned for type PostDatapointInternalServerError
const PostDatapointInternalServerErrorCode int = 500

/*PostDatapointInternalServerError Server error

swagger:response postDatapointInternalServerError
*/
type PostDatapointInternalServerError struct {
}

// NewPostDatapointInternalServerError creates PostDatapointInternalServerError with default headers values
func NewPostDatapointInternalServerError() *PostDatapointInternalServerError {

	return &PostDatapointInternalServerError{}
}

// WriteResponse to the client
func (o *PostDatapointInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
