// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostDatapointHandlerFunc turns a function with the right signature into a post datapoint handler
type PostDatapointHandlerFunc func(PostDatapointParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDatapointHandlerFunc) Handle(params PostDatapointParams) middleware.Responder {
	return fn(params)
}

// PostDatapointHandler interface for that can handle valid post datapoint params
type PostDatapointHandler interface {
	Handle(PostDatapointParams) middleware.Responder
}

// NewPostDatapoint creates a new http.Handler for the post datapoint operation
func NewPostDatapoint(ctx *middleware.Context, handler PostDatapointHandler) *PostDatapoint {
	return &PostDatapoint{Context: ctx, Handler: handler}
}

/*PostDatapoint swagger:route POST /metrics/{metricName} metrics postDatapoint

Save datapoint

Save datapoint

*/
type PostDatapoint struct {
	Context *middleware.Context
	Handler PostDatapointHandler
}

func (o *PostDatapoint) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostDatapointParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
