// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Datapoint datapoint
// swagger:model Datapoint
type Datapoint struct {

	// timestamp utc
	// Required: true
	TimestampUtc *int64 `json:"timestamp_utc"`

	// value
	// Required: true
	Value *int64 `json:"value"`
}

// Validate validates this datapoint
func (m *Datapoint) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTimestampUtc(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Datapoint) validateTimestampUtc(formats strfmt.Registry) error {

	if err := validate.Required("timestamp_utc", "body", m.TimestampUtc); err != nil {
		return err
	}

	return nil
}

func (m *Datapoint) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Datapoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Datapoint) UnmarshalBinary(b []byte) error {
	var res Datapoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
